name: ci
on: [push, pull_request, workflow_dispatch]
jobs:
  build-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node_version: [ 14.x ]
    name: Node ${{ matrix.node_version }} - on ${{ matrix.os }}
    env:
      NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run test
